config/routes.rb
Behave::Application.routes.draw do
  devise_for :users

  resources :testers
  resources :children

  root :to => 'home#index'

end

app/models/child.rb
class Child < ActiveRecord::Base
end

app/models/tester.rb
class Tester < ActiveRecord::Base
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable, :lockable

  # validates :name, :presence => true, :uniqueness => true
  validates :email, :presence => true, :uniqueness => true

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/widget.rb
class Widget < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  # GET /children
  # GET /children.json
  def index
    @children = Child.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @children }
    end
  end

  # GET /children/1
  # GET /children/1.json
  def show
    @child = Child.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @child }
    end
  end

  # GET /children/new
  # GET /children/new.json
  def new
    @child = Child.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @child }
    end
  end

  # GET /children/1/edit
  def edit
    @child = Child.find(params[:id])
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(params[:child])

    respond_to do |format|
      if @child.save
        format.html { redirect_to @child, notice: 'Child was successfully created.' }
        format.json { render json: @child, status: :created, location: @child }
      else
        format.html { render action: "new" }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /children/1
  # PUT /children/1.json
  def update
    @child = Child.find(params[:id])

    respond_to do |format|
      if @child.update_attributes(params[:child])
        format.html { redirect_to @child, notice: 'Child was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child = Child.find(params[:id])
    @child.destroy

    respond_to do |format|
      format.html { redirect_to children_url }
      format.json { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/testers_controller.rb
class TestersController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :json

  # GET /testers
  # GET /testers.json
  def index
    @testers = Tester.all
    respond_with @testers
  end

  # GET /testers/1
  # GET /testers/1.json
  def show
    @tester = Tester.find(params[:id])
    respond_with @tester
  end

  # GET /testers/new
  # GET /testers/new.json
  def new
    @tester = Tester.new
    respond_with @tester
  end

  # GET /testers/1/edit
  def edit
    @tester = Tester.find(params[:id])
    respond_with @tester
  end

  # POST /testers
  # POST /testers.json
  def create
    @tester = Tester.new(params[:tester])

    respond_with(@tester) do |format|
      if @tester.save
        format.html { redirect_to @tester, notice: 'Tester was successfully created.' }
        format.json { render json: @tester, status: :created, location: @tester }
      else
        format.html { render action: "new" }
        format.json { render json: @tester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /testers/1
  # PUT /testers/1.json
  def update
    @tester = Tester.find(params[:id])

    respond_with(@tester) do |format|
      if @tester.update_attributes(params[:tester])
        format.html { redirect_to @tester, notice: 'Tester was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @tester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testers/1
  # DELETE /testers/1.json
  def destroy
    @tester = Tester.find(params[:id])
    @tester.destroy

    respond_with(@tester) do |format|
      format.html { redirect_to testers_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
    when :notice then "success"
    when :error then "error"
    when :alert then "info"
    end
  end

end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nav_link_helper.rb
module NavLinkHelper

  def nav_link(title, path, html_options = {}, options = {})
    LinkGenerator.new(request, title, path, html_options, options).to_html
  end

  class LinkGenerator
    include ActionView::Helpers::UrlHelper

    def initialize(request, title, path, html_options = {}, options = {})
      @request      = request
      @title        = title
      @path         = path
      @html_options = html_options
      @options      = options
    end

    def to_html
      html = link

      if @options[:wrapper]
        html = content_tag(@options[:wrapper], html, :class => wrapper_classes)
      end

      html.html_safe
    end

    private

    def current_path
      comparable_path_for(@request.fullpath)
    end

    def link_path
      comparable_path_for(url_for(@path))
    end

    def segment_position
      if @options[:controller_segment]
        @options[:controller_segment] - 1
      elsif @options[:url_segment]
        @options[:url_segment]
      end
    end

    def path_controller
      controller_for(@path)
    end

    def current_controller
      controller_for(@request.path)
    end

    def segment_for(controller, path)
      if @options[:controller_segment]
        controller.split('/')[segment_position]
      elsif @options[:url_segment]
        path.split('/')[segment_position]
      end
    end

    def path_segment
      segment_for(path_controller, current_path)
    end

    def current_segment
      segment_for(current_controller, link_path)
    end

    def paths_match?
      current_path == link_path
    end

    def segments_match?
      path_segment && path_segment == current_segment
    end

    def selected?
      paths_match? || segments_match?
    end

    def selected_class
      @options[:selected_class] || 'selected'
    end

    def link_classes
      if @html_options[:class]
        @html_options[:class] + " #{selected_class}"
      else
        selected_class
      end
    end

    def html_options
      selected? ? @html_options.merge(:class => link_classes) : @html_options
    end

    def link
      link_to(@title, @path, html_options)
    end

    def wrapper_classes
      if selected?
        "#{selected_class} #{@options[:wrapper_class]}"
      else
        @options[:wrapper_class]
      end
    end

    def controller_for(path)
      Rails.application.routes.recognize_path(path)[:controller]
    end

    def comparable_path_for(path)
      if @options[:ignore_params]
        path.gsub(/\?.*/, '')
      else
        path
      end
    end
  end
end

app/helpers/testers_helper.rb
module TestersHelper
end

app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :references %><br />
    <%= f.text_field :references %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<h1>Listing children</h1>

<table>
  <tr>
    <th>Name</th>
    <th>References</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @children.each do |child| %>
  <tr>
    <td><%= child.name %></td>
    <td><%= child.references %></td>
    <td><%= link_to 'Show', child %></td>
    <td><%= link_to 'Edit', edit_child_path(child) %></td>
    <td><%= link_to 'Destroy', child, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Child', new_child_path %>

app/views/children/new.html.erb
<h1>New child</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @child.name %>
</p>

<p>
  <b>References:</b>
  <%= @child.references %>
</p>


<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

app/views/home/index.html.erb
<h1>Homepage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html lang="en"> 
<head> 
  <meta charset=utf-8>
  <title>Behavior Tracker</title> 

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application", "underscore" %>
  <%= csrf_meta_tag %>

  <script type="text/javascript">
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'GA ID GOES HERE']);
    _gaq.push(['_trackPageview']);
    _gaq.push(['_setSiteSpeedSampleRate', 100]); // Google Analytics > Content > Site Speed
   </script>
</head>
<body> 

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">BT</a>
        <div class="nav-collapse">
          <%= tabs %>

          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <a href="#"><%= current_user.email %></a> |
              <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path %> | 
              <%= link_to "Sign in", new_user_session_path %>
            <% end -%>
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="container master-container">

    <% [:notice, :error, :alert].each do |level| %>
      <% unless flash[level].blank? %>
        <div class="alert <%= flash_class(level) %>">
          <a class="close" data-dismiss="alert">×</a>
          <%= flash[level] %>
        </div>
      <% end %>
    <% end %>

    <section id="content"> 
      <%= yield %>
    </section> 

    <footer>
      <div class="row show-grid" title="Default three column layout">
        <div class="span4">
          A Flatland Lab Production
        </div>
        <div class="span4">
          A Flatland Lab Production
        </div>
        <div class="span4">
          A Flatland Lab Production
        </div>
      </div>
    </footer> 
  </div>
</body> 
</html> 

app/views/testers/_form.html.erb
<%= simple_form_for(@tester, :html => {:class => 'form-horizontal, well'}) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, :input_html => { :class => "span6" }, :hint => "Tester Name" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
  </div>
<% end %>

app/views/testers/edit.html.erb
<h1>Editing tester</h1>

<%= render 'form' %>

<%= link_to 'Show', @tester %> |
<%= link_to 'Back', testers_path %>

app/views/testers/index.html.erb
<h1>Listing testers</h1>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @testers.each do |tester| %>
  <tr>
    <td><%= tester.name %></td>
    <td><%= link_to 'Show', tester %></td>
    <td><%= link_to 'Edit', edit_tester_path(tester) %></td>
    <td><%= link_to 'Destroy', tester, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tester', new_tester_path %>

app/views/testers/new.html.erb
<h1>New tester</h1>

<%= render 'form' %>

<%= link_to 'Back', testers_path %>

app/views/testers/show.html.erb
<p>
  <b>Name:</b>
  <%= @tester.name %>
</p>


<%= link_to 'Edit', edit_tester_path(@tester) %> |
<%= link_to 'Back', testers_path %>